title: Yaoze Zou
remote_theme: riggraz/no-style-please
url: https://yzzou.github.io
description: > # description of the site (multiple lines allowed)
  replace description here

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed